import Head from 'next/head'
// import Image from 'next/image'
import styles from 'styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <div className="row">
          <div className="col-md-3">
            <h1>hehehehehehee</h1>
            <button className="btn btn-primary">Test bootstrap</button>
          </div>
        </div>
      </div>
    </div>
  )
}
